# Generated by Django 5.2.10 on 2026-03-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_merge_0002_alter_featured_image_0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
