# Generated by Django 5.2.10 on 2026-06-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_vendor_pricehistory_pricealert"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="categories/"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="featured_image",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="products/"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(max_length=500, upload_to="products/"),
        ),
    ]
