# Generated by Django 5.2.10 on 2026-06-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_category_image_alter_product_featured_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="approved",
                help_text="Admin must approve new/updated products before they go live",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="pending_deletion",
            field=models.BooleanField(
                default=False,
                help_text="Seller requested deletion, awaiting admin confirmation",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="pending_update_data",
            field=models.JSONField(
                blank=True,
                help_text="Stores proposed field changes until admin approves the update",
                null=True,
            ),
        ),
    ]
