# Generated by Django 5.2.10 on 2026-06-18 05:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "region",
                    models.CharField(
                        help_text="e.g. South West, Littoral, Centre", max_length=100
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "base_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=500,
                        help_text="Base delivery fee in FCFA",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "free_delivery_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=25000,
                        help_text="Free delivery for orders above this amount",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "estimated_days_min",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "estimated_days_max",
                    models.IntegerField(
                        default=3,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Delivery Zone",
                "verbose_name_plural": "Delivery Zones",
                "db_table": "delivery_zones",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Town or quarter name", max_length=200),
                ),
                ("city", models.CharField(max_length=100)),
                (
                    "surcharge",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Additional fee for this area",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="delivery.deliveryzone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery Area",
                "verbose_name_plural": "Delivery Areas",
                "db_table": "delivery_areas",
                "ordering": ["city", "name"],
                "unique_together": {("zone", "name", "city")},
            },
        ),
    ]
