# Generated by Django 5.2.10 on 2026-06-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("seller", "Seller"), ("admin", "Admin")],
                default="user",
                max_length=10,
            ),
        ),
    ]
