# Generated by Django 5.2.10 on 2026-06-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="banner",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="vendors/banners/"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="logo",
            field=models.ImageField(
                blank=True, max_length=500, null=True, upload_to="vendors/logos/"
            ),
        ),
    ]
